/**
 * Created by Wenba on 2017/3/27.
 */
module.exports ={
  routes:[
    {
      path:'/',
      component:require('./components/pages/News.vue'),
      children:[
        {
          path:'/news/top',
          component:require('./components/newsPage/Top.vue')
        }
      ]
    },
    {
      path:'/news',
      component:require('./components/pages/News.vue'),
      children:[
        {
          path:'/news/top',
          component:require('./components/newsPage/Top.vue')
        },
        {
          path:'/news/shehui',
          component:require('./components/newsPage/Shehui.vue')
        },
        {
          path:'/news/guonei',
          component:require('./components/newsPage/Guonei.vue')
        },
        {
          path:'/news/guoji',
          component:require('./components/newsPage/Guoji.vue')
        },
        {
          path:'/news/tiyu',
          component:require('./components/newsPage/Tiyu.vue')
        },
        {
          path:'/news/keji',
          component:require('./components/newsPage/Keji.vue')
        },
        {
          path:'/news/caijing',
          component:require('./components/newsPage/Caijing.vue')
        }
      ]
    },
    {
      path:'/movie/hot',
      component:require('./components/pages/Movie.vue'),
      children:[
        {
          path:'/',
          component:require('./components/moviePages/Hot.vue')
        }
      ]
    },
    {
      path:'/music',
      component:require('./components/pages/Music.vue')
    },
    {
      path:'/book',
      component:require('./components/pages/Book.vue'),
      children:[
        {
          path:'/',
          component:require('./components/bookPage/Wenxue.vue')
        },
        {
          path:'/book/wenxue',
          component:require('./components/bookPage/Wenxue.vue')
        },
        {
          path:'/book/lishi',
          component:require('./components/bookPage/Lishi.vue')
        },
        {
          path:'/book/zhexue',
          component:require('./components/bookPage/Zhexue.vue')
        },
        {
          path:'/book/jiaoyu',
          component:require('./components/bookPage/Jiaoyu.vue')
        },
        {
          path:'/book/sanwen',
          component:require('./components/bookPage/Sanwen.vue')
        },
        {
          path:'/book/mingzhu',
          component:require('./components/bookPage/Mingzhu.vue')
        },
      ]
    }

  ]
}
